name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache dependencies
      - name: prime-cache-287d85b
        id: cache-step
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-287d85b

      # Echo cache hit/miss
      - name: Echo cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Install dependencies (example for Node.js)
      - name: Install dependencies
        run: npm install
