name: CI Cache Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-287d85b

      - name: prime-cache-287d85b
        run: echo "Cache hit:${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
