name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-287d85b
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: cache-287d85b

      - name: Echo cache hit/miss
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Install dependencies
        run: npm install

      - name: Run build (example)
        run: npm run build
